### ISSUE TITLE
Unresolved log message key jaspic.provider_unable_to_load_authmodule

### ISSUE THREAD

**Issue by dmatej** [eclipse-ee4j/epicyro#1]
```
[2024-03-27T11:38:35.644810Z] [GF 7.0.14-SNAPSHOT] [WARNING] [] [org.glassfish.epicyro.config.helper.ObjectUtils] [tid: _ThreadID=39 _ThreadName=http-listener-1(5)] [levelValue: 900] [[
  jaspic.provider_unable_to_load_authmodule]]
```

**Comment by dmatej** [comment]
Maybe there are also other such messages, I can take a look soon.

**Comment by arjantijms** [comment]
As given it does already look relatively clear what it says just by the key name, but obviously we can do better there.

**Comment by dmatej** [comment]
> As given it does already look relatively clear what it says just by the key name, but obviously we can do better there.

The problem was that I did not see in logs what class is missing.
